#
# Module manifest for module 'Virten.net.VimAutomation'
#
# Generated by: Florian Grehl @virten
#
# Generated on: 03.09.2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Virten.net.VimAutomation'

# Version number of this module.
ModuleVersion = '1.3.0'

# ID used to uniquely identify this module
GUID = 'c5696a1b-2faa-4b1b-a4ca-d4d993dbb013'

# Author of this module
Author = 'Florian Grehl @virten'

# Company or vendor of this module
CompanyName = 'virten.net'

# Copyright statement for this module
Copyright = '(c) 2017 Florian Grehl. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Virten.net PowerCLI Automation Module'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '3.0'

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

